#!/usr/bin/python3
import math
import sys

def factorize(n):
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return [i, int(n/i)]

for fn in sys.argv[1:]:
    with open(fn, 'r') as f:
        for num in f.readlines():
            num = int(num.strip())
            result = factorize(num)
            if result:
                print('{}={}*{}'.format(num, result[0], result[1]))
