#!/usr/bin/python3
import sys
from math import sqrt

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(sqrt(n))+1):
        if n % i == 0:
            return False
    return True

def factors(n):
    if is_prime(n):
        return n
    for i in range(2, int(sqrt(n))+1):
        if n % i == 0:
            return i
    return n

if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    with open(sys.argv[1], 'r') as file:
        for line in file:
            n = int(line)
            factor = factors(n)
            print("{}={}*{}".format(n, factor, n//factor))
