#!/usr/bin/python3
import sys
from prime import factor

with open("prime.txt", 'r') as file:
    lp = set(map(int, file.readline().strip().split(",")))

if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)
    with open(sys.argv[1], 'r') as file:
        lpi = list(map(int, file.readlines()))
    for i in lpi:
        j = factor(i, lp)
        print(f"{i}={i//j}*{j}")
